# Generated by Django 4.2.5 on 2023-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomImage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='Room_image',
            field=models.ImageField(null=True, upload_to='photo/roomimage'),
        ),
    ]
