# Generated by Django 4.2.5 on 2023-10-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_remove_room_roomimage_alter_room_expiration_date'),
        ('RoomImage', '0002_roomimage_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.room'),
        ),
    ]
