# Generated by Django 4.2.5 on 2023-11-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Room', '0012_alter_room_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saveroom_id', models.CharField(blank=True, max_length=250)),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaveRoomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.room')),
                ('saveroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaveRoom.saveroom')),
            ],
        ),
    ]
