# Generated by Django 4.2.5 on 2023-11-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoaiThanhToan', models.TextField(max_length=100, unique=True)),
            ],
        ),
    ]
