# Generated by Django 4.2.5 on 2023-11-26 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedBack', '0002_alter_feedback_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 12, 48, 49, 734299, tzinfo=datetime.timezone.utc)),
        ),
    ]
