# Generated by Django 4.2.6 on 2023-11-28 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedBack', '0009_alter_feedback_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 9, 31, 27, 424239, tzinfo=datetime.timezone.utc)),
        ),
    ]
