# Generated by Django 4.2.5 on 2023-12-07 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedBack', '0011_alter_feedback_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 4, 8, 3, 920849, tzinfo=datetime.timezone.utc)),
        ),
    ]
