# Generated by Django 4.2.5 on 2023-10-19 05:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RoomCategory', '0001_initial'),
        ('RoomArea', '0001_initial'),
        ('RoomImage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Room', models.CharField(max_length=100, unique=True)),
                ('Address', models.CharField(max_length=250, unique=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Price_deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2023, 11, 2, 5, 52, 18, 263936, tzinfo=datetime.timezone.utc))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomCategory.roomcategory')),
                ('roomarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomArea.roomarea')),
                ('roomimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomImage.roomimage')),
            ],
        ),
    ]
