# Generated by Django 4.2.5 on 2023-10-19 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mainimage',
            field=models.ImageField(null=True, upload_to='photo/mainimage'),
        ),
        migrations.AlterField(
            model_name='room',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 6, 39, 19, 51066, tzinfo=datetime.timezone.utc)),
        ),
    ]
