# Generated by Django 4.2.5 on 2023-10-19 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_room_mainimage_alter_room_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomimage',
        ),
        migrations.AlterField(
            model_name='room',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 6, 49, 39, 617976, tzinfo=datetime.timezone.utc)),
        ),
    ]
