# Generated by Django 4.2.5 on 2023-10-19 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0004_alter_room_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 7, 58, 5, 34672, tzinfo=datetime.timezone.utc)),
        ),
    ]
