# Generated by Django 4.2.5 on 2023-11-08 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_alter_room_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 15, 7, 15, 486415, tzinfo=datetime.timezone.utc)),
        ),
    ]
