# Generated by Django 4.2.5 on 2023-11-09 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0008_alter_room_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 4, 50, 55, 610636, tzinfo=datetime.timezone.utc)),
        ),
    ]
