# Generated by Django 4.2.5 on 2023-11-18 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0011_room_slug_alter_room_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 9, 39, 25, 81508, tzinfo=datetime.timezone.utc)),
        ),
    ]
