# Generated by Django 4.2.5 on 2023-11-24 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0012_alter_room_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 6, 21, 51, 886712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='photo/mainimage'),
        ),
    ]
