# Generated by Django 4.2.5 on 2023-11-24 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0013_alter_room_expiration_date_alter_room_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 12, 3, 29, 907511, tzinfo=datetime.timezone.utc)),
        ),
    ]
