# Generated by Django 4.2.5 on 2023-11-24 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0015_alter_room_expiration_date_alter_room_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 12, 12, 1, 295030, tzinfo=datetime.timezone.utc)),
        ),
    ]
