# Generated by Django 4.2.5 on 2023-11-27 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0024_alter_room_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 11, 59, 49, 112955, tzinfo=datetime.timezone.utc)),
        ),
    ]
