# Generated by Django 4.2.5 on 2023-11-27 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0025_alter_room_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 14, 6, 13, 849032, tzinfo=datetime.timezone.utc)),
        ),
    ]
