# Generated by Django 4.2.5 on 2023-12-07 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0028_alter_room_expiration_date_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 4, 8, 3, 905141, tzinfo=datetime.timezone.utc)),
        ),
    ]
