# Generated by Django 4.2.5 on 2023-10-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_LoaiPhong', models.CharField(max_length=200, unique=True)),
                ('Url_LoaiPhong', models.ImageField(blank=True, upload_to='photo/categories')),
            ],
            options={
                'verbose_name': 'Room Category',
                'verbose_name_plural': 'Room Categories',
            },
        ),
    ]
