# Generated by Django 4.2.5 on 2023-11-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomCategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True, unique=True),
        ),
    ]
