# Generated by Django 4.2.5 on 2023-11-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomCategory', '0002_roomcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='slug',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
