# Generated by Django 4.2.5 on 2023-10-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
